version: '3.5'

services:
  viiidb-api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: viiidb-api
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - viiidb

networks:
  viiidb:
    external:
      name: viiidb