version: '3.5'

services:
  viiidb-api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: viiidb-api
    volumes:
      - ./:/app
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    networks:
      - viiidb

networks:
  viiidb:
    external:
      name: viiidb